const text = ['An orange is a type of citrus fruit known for its bright orange color, round shape, and juicy, sweet flavor. It belongs to the Rutaceae family and is cultivated in many parts of the world, particularly in warm climates. Oranges are a popular fruit enjoyed fresh, juiced, or used in various culinary dishes and beverages. They are rich in vitamin C, fiber, and other nutrients, making them a nutritious addition to a balanced diet.','An apple is a round fruit with firm, crisp flesh and typically red, green, or yellow skin. It belongs to the Rosaceae family and is grown on apple trees, which are cultivated in temperate climates worldwide. Apples come in many varieties, each with its own unique flavor, texture, and appearance. They are often enjoyed fresh as a healthy snack but can also be used in cooking, baking, and juicing. Apples are a good source of dietary fiber, vitamin C, and various antioxidants, making them a nutritious addition to a balanced diet.',`
A banana is a long, curved fruit with a soft, creamy flesh inside a yellow or sometimes green skin. It grows on a flowering plant in the genus Musa, which is native to tropical regions of Southeast Asia but is now cultivated in many warm climates around the world. Bananas are one of the most popular fruits globally, prized for their sweet taste, convenient packaging, and nutritional value. They are rich in potassium, vitamins, and dietary fiber, making them a healthy snack choice. Bananas can be eaten raw, added to smoothies, baked into bread and desserts, or used in savory dishes.`,`A lemon is a small, yellow citrus fruit with a sour and tangy flavor. It belongs to the Rutaceae family and is native to South Asia. Lemons are widely cultivated around the world for their culinary and medicinal uses. They are rich in vitamin C and antioxidants, making them a popular ingredient in cooking, baking, beverages, and household cleaning products. Lemon juice is often used to add acidity and flavor to dishes, while the zest (the outermost layer of the peel) can be grated to add a fragrant citrus aroma. Lemons are also used to make lemonade, preserves, salad dressings, and marinades.`]
const val = (e,value) => e.currentTarget.getAttribute(`${value}`)
$('img').click(function (e) {
  $('body').css('backgroundColor',val(e,'value'))
  $('h1').text(val(e,'name'))
  console.log(`./images/${val(e,'num')}.jfif`);
  $('.text img').attr('src',`./images/${val(e,'num')}.jfif`)
  $('.text p').text(text[val(e,'num') -1])
});